import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createAppServer } from '../server.mjs';

test('user page exposes the complete test flow with visible answer copy and no implementation language', async (t) => {
  const dir = await mkdtemp(join(tmpdir(), 'picky-ui-'));
  const app = createAppServer({ archivePath: join(dir, 'tests.json') });
  await new Promise((resolve) => app.listen(0, '127.0.0.1', resolve)); t.after(() => app.close());
  const base = `http://127.0.0.1:${app.address().port}`;
  const html = await fetch(base).then((response) => response.text());
  const css = await fetch(`${base}/styles.css`).then((response) => response.text());
  const touchCss = await fetch(`${base}/touch-fixes.css`).then((response) => response.text());
  const compactCss = await fetch(`${base}/intro-compact.css`).then((response) => response.text());
  const previewCss = await fetch(`${base}/share-preview.css`).then((response) => response.text());
  const appJs = await fetch(`${base}/app.js`).then((response) => response.text());
  assert.match(html, /你到底有多挑食/);
  for (const label of ['超爱吃', '可以吃', '坚决不吃', '没吃过']) assert.match(html, new RegExp(label));
  for (const forbidden of ['无需登录', '本地存储', '匿名统计', '自适应算法']) assert.doesNotMatch(html, new RegExp(forbidden));
  assert.match(html, /name="viewport"/);
  assert.match(html, /输入好友配对码/);
  assert.match(html, /开始双人匹配/);
  assert.match(html, /touch-fixes\.css\?v=2/);
  assert.match(html, /intro-compact\.css\?v=1/);
  assert.match(html, /share-preview\.css\?v=1/);
  assert.match(html, /brand\.css\?v=2/);
  assert.match(html, /app\.js\?v=brand1/);
  assert.match(html, /\/assets\/picky-logo\.png/);
  assert.match(html, /COPYRIGHT © 2026 WZRICE\.CN · ALL RIGHTS RESERVED/);
  assert.match(html, /直接查看匹配度/);
  assert.match(html, /我的测试码/);
  assert.match(html, /对方测试码/);
  assert.match(css, /color:\s*var\(--ink\)/);
  assert.match(css, /prefers-reduced-motion/);
  assert.match(touchCss, /@media\s*\(hover:\s*none\)/);
  assert.match(touchCss, /\.answer-button:hover[^}]*background:\s*var\(--paper\)/);
  assert.match(appJs, /isPublicCode\(pendingPairCode\).*showIntro/s);
  assert.match(appJs, /QRCode\.toCanvas/);
  assert.match(appJs, /errorCorrectionLevel:\s*'H'/);
  assert.match(appJs, /card\.pairUrl/);
  assert.match(appJs, /context\.rotate\(2 \* Math\.PI \/ 180\)/);
  assert.match(appJs, /drawImage\(qrCanvas,\s*0,\s*0,\s*260,\s*260\)/);
  assert.match(appJs, /扫我测匹配度 ↗/);
  assert.match(appJs, />分享链接</);
  assert.match(appJs, />保存图片</);
  assert.match(appJs, /canvas\.toDataURL\('image\/jpeg',\s*\.92\)/);
  assert.match(appJs, /长按图片保存到相册/);
  assert.match(appJs, /MicroMessenger/i);
  assert.match(appJs, /pickShareTheme\(\)/);
  assert.match(appJs, /brand-lockup/);
  assert.match(appJs, /context\.drawImage\(brandLogo/);
  assert.doesNotMatch(appJs, /MY TABLE PERSONALITY/);
  assert.doesNotMatch(appJs, /COPYRIGHT © 2026/);
  assert.match(appJs, /快来测测我们的饭桌默契度/);
  assert.doesNotMatch(appJs, /navigator\.share/);
  assert.match(previewCss, /\.share-preview-overlay/);
  assert.match(compactCss, /max-height:\s*760px/);
  assert.match(compactCss, /\.intro-screen \.rules\s*\{[^}]*grid-template-columns:\s*1fr 1fr/);
  assert.doesNotMatch(appJs, /JSON\.parse\(localStorage\.getItem\(STORAGE_KEY\)\)/);
});

test('client modules are served to the browser', async (t) => {
  const app = createAppServer(); await new Promise((resolve) => app.listen(0, '127.0.0.1', resolve)); t.after(() => app.close());
  const response = await fetch(`http://127.0.0.1:${app.address().port}/modules/foods.js`);
  assert.equal(response.status, 200);
  assert.match(await response.text(), /export const FOODS/);
});

test('brand logo is served as a transparent PNG asset', async (t) => {
  const app = createAppServer(); await new Promise((resolve) => app.listen(0, '127.0.0.1', resolve)); t.after(() => app.close());
  const response = await fetch(`http://127.0.0.1:${app.address().port}/assets/picky-logo.png`);
  assert.equal(response.status, 200);
  const bytes = new Uint8Array(await response.arrayBuffer());
  assert.deepEqual([...bytes.slice(0, 8)], [137, 80, 78, 71, 13, 10, 26, 10]);
});
